; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = RadioV01
data_dir = RadioV01/data

[muse_radio_common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r8
framework =
	arduino
	espidf
lib_extra_dirs = libraries
lib_ignore = ArduinoHttpClient
upload_speed = 921600
monitor_speed = 115200
board_upload.flash_size = 8MB
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
	-IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
	-IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
	-IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/soc/esp32s3/register
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM
	-DUSE_HSPI_PORT
lib_ldf_mode = deep+

[env:muse_radio]
extends = muse_radio_common
build_flags =
	${muse_radio_common.build_flags}
	-DENABLE_USB_AUDIO=1

[env:muse_radio_usb_display_poc]
extends = muse_radio_common
build_flags =
	${muse_radio_common.build_flags}
	-DENABLE_USB_AUDIO=1
	-DENABLE_USB_MIC=1
	-DENABLE_USB_DISPLAY=1
	-DAUDIO_ENABLE_I2S_RX=1
	-DMUSE_FIRMWARE_VERSION=\"V1.8-display-poc\"
	-DMUSE_IMPROV_VERSION=\"1.8-display-poc\"

[env:muse_radio_spotify_poc]
extends = muse_radio_common
build_flags =
	${muse_radio_common.build_flags}
	-DENABLE_SPOTIFY_CONNECT=1
	-DCSPOT_ZEROCONF_PORT=8080
	-DSPI_FREQUENCY=27000000
	-include components/cspot_component/bell_compat.hpp
	-std=gnu++20
build_unflags =
  -std=gnu++11
  -std=gnu++14
  -std=gnu++17

[env:muse_radio_airplay_poc]
extends = muse_radio_common
build_flags =
	${muse_radio_common.build_flags}
	-DENABLE_AIRPLAY=1
	-DSPI_FREQUENCY=27000000
	-Imanaged_components/espressif__mdns/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/esp_event/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/esp_netif/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/esp_timer/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/mbedtls/port/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/mbedtls/mbedtls/include
	-IC:/Users/olivi/.platformio/packages/framework-espidf/components/pthread/include
	-std=gnu++20
build_unflags =
  -std=gnu++11
  -std=gnu++14
  -std=gnu++17
