[platformio]
src_dir = RadioV01
data_dir = RadioV01/data

[env:muse_radio]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r8
framework = arduino
lib_extra_dirs = libraries
lib_ignore = ArduinoHttpClient
upload_speed = 921600
monitor_speed = 115200
board_upload.flash_size = 8MB
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
  -IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
  -IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
  -IC:/Users/olivi/.platformio/packages/framework-arduinoespressif32-libs/esp32s3/include/soc/esp32s3/register
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_RUNNING_CORE=1
  -DARDUINO_EVENT_RUNNING_CORE=1
  -DCORE_DEBUG_LEVEL=0
  -DBOARD_HAS_PSRAM
  -DUSE_HSPI_PORT
lib_ldf_mode = deep+
